import "./globals.css";
import Head from "next/head";
import Navbar from "./components/Header";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </Head>
            <body>
                <Navbar/>
                {children}
            </body>
        </html>
    );
}
